Verify that bolt's modules are valid
Github actions do not currently verify whether bolt's module dependencies are valid.  In other worlds, bolt uses a number of puppet modules and these can be out-of-date or even missing dependencies.  This commit adds an extra step to CI that checks for missing dependecies.

Signed-off-by: Gavin Didrichsen <gavin.didrichsen@gmail.com>

diff --git a/.github/workflows/unit.yaml b/.github/workflows/unit.yaml
--- a/.github/workflows/unit.yaml
+++ b/.github/workflows/unit.yaml
@@ -45,5 +45,14 @@ jobs:
       - name: Install modules
         if: steps.modules.outputs.cache-hit != 'true'
         run: bundle exec r10k puppetfile install
-      - name: Unit tests
-        run: bundle exec rake tests:unit
+      - name: Check installed modules for errors
+        run: |
+          set -e
+          output=$(bundle exec puppet module list --modulepath modules)
+          echo "$output"
+          if echo "$output" | grep -q "Warning: Missing dependency"; then
+            echo "Error: Missing dependencies found in installed modules."
+            exit 1
+              fi
+          - name: Unit tests
+            run: bundle exec rake tests:unit
